export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  "A flamingo standing on one leg wearing a top hat and monocle, digital art",
"A vintage record player with plants growing out of it, photography",
"A cartoon-style illustration of a corgi driving a tiny car, digital art",
"A surreal painting of a mermaid riding a bicycle through a desert, oil on canvas",
"A sci-fi inspired 3D render of a futuristic city with flying cars, digital art",
"A photograph of a jellyfish glowing in the dark waters of the ocean, macro lens",
"A portrait of a pug wearing a crown and sitting on a throne, mixed media",
"A landscape painting of a mountain range with neon lights in the sky, acrylic on canvas",
"A photo of a futuristic robot bartender mixing a drink, digital art",
"A drawing of a dragon made entirely out of leaves and flowers, colored pencil on paper",
"An abstract painting of a rainbow-colored waterfall, watercolor on paper",
"A photo of a cat wearing sunglasses sitting in a canoe on a lake, digital art",
"A 3D render of a magical forest with glowing mushrooms and fireflies, digital art",
"A digital portrait of a person with a cybernetic arm and neon hair, digital art",
"A surreal painting of a giant rabbit sitting in a teacup, acrylic on canvas",
"A photograph of a sunset over the ocean with a palm tree silhouette in the foreground, landscape photography",
"A cartoon-style illustration of a bear riding a skateboard, digital art",
"A painting of a unicorn with a rainbow-colored mane, oil on canvas",
"A photo of a panda eating sushi, close-up with macro lens",
"A 3D render of a futuristic space station with a giant hologram in the center, digital art",

];